### ISSUE TITLE
Update time for Google Drive

### ISSUE THREAD

**Issue by eskdale** [BeanYoung/PoweredBy.Cloud#1]
Hi Bean - Very excited about your PoweredBy.Cloud - I do however see a long delay between updating the file on the Google Drive and the time before the update is shown by the URL link.  A minute or two would be OK but it appears to be hours.  When I first tested it - I didn't notice this.  I am refreshing the cache so that is not the issue.
To use it for my application it really needs to be within a few minutes at most.
There are a couple of spelling mistakes on the Site which otherwise spoil its professional look
Upload and Browse are misspelled.
What are your plans as I've not seen any updates since the initial release
 (jon@eskdale.org)

**Comment by BeanYoung** [comment]
Hi @eskdale , very sorry for the inconvenience.
PoweredBy.Cloud's network is based on cloudflare.com and cloudflare.com has 2 hours cache time by default. So if you update files in google drive, it will take 2 hours at most to get latest version of your files. Currently I add the body hash of file to URL as a query string, so you can get latest URL from dashboard after you update files in google drive. PoweredBy.Cloud will sync file body hash with google drive in seconds.  This is only a temporary solution. If you still meet a long delay, please let me know.
Currently I'm working on two features. First feature is using cloudflare.com's api to refresh cloudflare.com cache after sync with google drive, then we can use the same URL to get latest file version after file is changed in google drive and one drive in seconds. Second feature is S3 compatible api, that means we can use official aws s3 sdk and command line tools to manage files in google drive and one drive.
I can only work on this project when my baby is sleeping, so I just have a slow progress .
Really thank you for your feedback and support! If you have any ideas or issues, please let me know!

**Comment by eskdale** [comment]
Hi Bean,
Thank you for your fast response - appreciated
I see you have corrected the small spelling issues - Nice thanks
I'm seeing a lot greater than the 2 hours as last time I modified a file
yesterday I didn't see it change all day but it had changed by today
Similarly I modified a file which must be about 8 hrs ago and it still
hasn't changed

https://sailwave.stdcdn.com/49er.htm?h=88ee9a0334d13698f5e58e3d09581c68
<https://mailtrack.io/trace/link/bfc6305626358ab210cd21b271967e54b9e2cd47?url=https%3A%2F%2Fsailwave.stdcdn.com%2F49er.htm%3Fh%3D88ee9a0334d13698f5e58e3d09581c68&userId=2430811&signature=09d7dd0bcf0f01c7>

This displays as
[image: image.png]

with the year as 2020

I edited the file on the google drive
As you can see the year is 2021
[image: image.png]

Looking at the Google Drive that has been there since 11 am so that is
nearly 9 hours and it hasn't changed

[image: image.png]

I appreciate all your work on this - The use case that I envisage for it is
for publishing results of Sailing competitions/Events
I am the author of the Sailwave scoring Program www.sailwave.com
<https://mailtrack.io/trace/link/c6a50a16e1221be7359b6af4c6c33fd01c07ff82?url=http%3A%2F%2Fwww.sailwave.com&userId=2430811&signature=d8e74dbc1b99f626>
Many
of the very large events have there own websites which hosts the HTML pages
generated by Sailwave
But there are many small events and clubs which although they have a
website can't host quickly an HTML page e.g. Wordpress sites and similar.
Built into Sailwave is the option to publish to Sailwave site so results
are immediately available on the Web.
This uses ftp with the password built into Sailwave so its not known and
ideally only results from Sailwave program can post there.
It works well but there are 3 issues

   - There is nothing stopping some malicious person overwriting your
   results (Not that it has ever been a problem but it could be)
   - You can only write results there you can't delete them - you can
   overwrite them with newer though.
   - You can't host images

It is popular still though and there are nearly 14K sets of results on the
Sailwave server over the last 6 years

It would be wonderful if the users could host the results and images on
their own Google Drive so that they are secure and they have control over
them
To that effect, I would like to add the option in the publish menu of
Sailwave to Publish to Poweredby.Cloud if you agree.

Sailwave is used around the world including China and is supplied free of
charge.
The only thing I get out of it is that I enjoy giving back to the sport and
I do get some expenses paid invitations to some events to score them for
the organisers.

I hope your baby is doing well - I have just got my first Grandchild
although with the current lockdown I haven't been able to see it yet.

If there is anything I can do to help please let me know

Many Thanks

Jon

Jon Eskdale
07530 112233
Skype "eskdale"

**Comment by BeanYoung** [comment]
Hi Jon,

Thank you for your feedback.

Seems that this is a google drive api issue, and I saw someone has reported to google team recently. The issue is google's notification on file changes is not working. Currently I create a crontab job to sync file update from google every 1 minute. I will follow this issue and if there are any update, I will ping you.

You really did a great job on www.sailwave.com and I think PoweredBy.Cloud can help users to serve static files. It's my pleasure to be recommended by www.sailwave.com.

Hope you and your family doing well, especially during this covid-19 period.

Many thanks.

**Comment by eskdale** [comment]
Hi Bean,

Many thanks - It appears to be working fine this morning.
It made a couple of tests and its updating in less than a minute

Thanks - I sincerely hope all your family are safe - Mine are fine but I do
worry about my 96yr old Father.
Let's hope we can get a bit of normality soon.

Thanks
Jon

Jon Eskdale
07530 112233
Skype "eskdale"

**Comment by eskdale** [comment]
[image: image.png]

This is what I'm seeing

Just for your info


Jon Eskdale
07530 112233
Skype "eskdale"
